apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-grafana-pvc
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.grafanaPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.grafanaPvc.storageClass | quote }}
