apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-traefik
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.traefik.type }}
  selector:
    app: traefik
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.traefik.ports | toYaml | nindent 2 }}
