apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.3
          args:
            - "--accesslog"
            - "--api.insecure=false"
            - "--providers.kubernetescrd"
            - "--providers.kubernetesingress"
            - "--entrypoints.web.address=:80" 
            - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.certificate.acme.tlschallenge"
            - "--certificatesresolvers.certificate.acme.email=PLACEHOLDER_LE-EMAIL"
            - "--certificatesresolvers.certificate.acme.storage=acme.json"
            # Only needed to test the configuration, comment out the line to receive a real certificate.
            #- "--certificatesresolvers.certificate.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE