grafana:
  grafana:
    image:
      repository: grafana/grafana
      tag: latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 250m
        memory: 750Mi
  podSecurityContext:
    fsGroup: 472
    supplementalGroups:
    - 0
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
hznCore:
  hznCore:
    args:
    - -s
    image:
      repository: docker.io/opennms/horizon
      tag: 33.1.3
    imagePullPolicy: IfNotPresent
  initOverlayConfig:
    image:
      repository: quay.io/labmonkeys/git
      tag: 2.45.2.b3360
  podSecurityContext:
    fsGroup: 10001
    sysctls:
    - name: net.ipv4.ping_group_range
      value: 0 10001
  replicas: 1
hznCoreActivemqTcp:
  ports:
  - name: grpc
    port: 61616
    protocol: TCP
    targetPort: 61616
  type: LoadBalancer
hznCoreConfig:
  gitBranch: main
  gitHost: github.com
  gitRepo: NotVyx/COM617-Config
  javaOpts: -Xmx2048m -XX:MaxMetaspaceSize=512m -agentlib:jdwp=transport=dt_socket,server=y,address=*:8001,suspend=n
  opennmsDbname: opennms
  opennmsDbpass: 0p3nNM5
  opennmsDbuser: opennms
  opennmsTimeseriesStrategy: rrd
  postgresHost: 172.16.15.178
  postgresPassword: 0p3nNM5
  postgresPort: "5432"
  postgresUser: opennms
  serviceName: hzn-core
  tz: Europe/London
hznCoreKarafTcp:
  ports:
  - name: karaf
    port: 8101
    targetPort: 0
  type: ClusterIP
hznCoreWebappTcp:
  ports:
  - name: webapp
    port: 8980
    protocol: TCP
    targetPort: 8980
  type: ClusterIP
kubernetesClusterDomain: cluster.local
pvc:
  grafanaPvc:
    storageClass: local-path
    storageRequest: 1Gi
  hznData:
    storageClass: local-path
    storageRequest: 5Gi
  hznDeploy:
    storageClass: local-path
    storageRequest: 5Gi
  hznFs:
    storageClass: local-path
    storageRequest: 5Gi
  hznImports:
    storageClass: local-path
    storageRequest: 5Gi
  hznLogs:
    storageClass: local-path
    storageRequest: 5Gi
  hznOverlay:
    storageClass: local-path
    storageRequest: 5Gi
traefik:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 443
  replicas: 1
  traefik:
    args:
    - --api.insecure=true
    - --log.level=DEBUG
    - --accesslog
    - --providers.kubernetesingress
    - --entrypoints.web.address=:80
    - --entrypoints.web.http.redirections.entryPoint.to=websecure
    - --entrypoints.websecure.address=:443
    - --certificatesresolvers.resolver.acme.tlschallenge
    - --certificatesresolvers.resolver.acme.email=support@forrest.one
    - --certificatesresolvers.resolver.acme.storage=acme.json
    containerSecurityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - ALL
    image:
      repository: traefik
      tag: v3.3
  type: LoadBalancer
traefikAccount:
  serviceAccount:
    annotations: {}
