---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hzn-core-config
data:
  TZ: "Europe/London"
  OPENNMS_TIMESERIES_STRATEGY: "rrd"
  POSTGRES_HOST: PLACEHOLDER_POSTGREHOST
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "opennms"
  POSTGRES_PASSWORD: PLACEHOLDER_POSTGREPASSWORD
  OPENNMS_DBNAME: "opennms"
  OPENNMS_DBPASS: PLACEHOLDER_ONMSPASSWORD
  OPENNMS_DBUSER: "opennms"
  SERVICE_NAME: "hzn-core"
  GIT_REPO: "NotVyx/COM617-Config"
  GIT_HOST: "github.com"
  GIT_BRANCH: "main"
  JAVA_OPTS: "-Xmx2048m -XX:MaxMetaspaceSize=512m -agentlib:jdwp=transport=dt_socket,server=y,address=*:8001,suspend=n"
