apiVersion: v1
kind: Service
metadata:
  name: hzn-core-activemq-tcp
  labels:
    app: hzn-core
spec:
  ports:
   - protocol: TCP
     port: 61616
     targetPort: 61616
     name: activemq
  selector:
    app: hzn-core
  type: LoadBalancer
