---
apiVersion: v1
kind: Service
metadata:
  name: hzn-core-webapp-tcp
  labels:
    app: hzn-core
spec:
  ports:
    - port: 8980
      targetPort: 8980
      protocol: TCP
      name: webapp
#    - port: 8990
#      targetPort: 8990
#      protocol: TCP
#      name: grpc
  selector:
    app: hzn-core
  type: ClusterIP
