---
http-url: "https://onms.forrest.one/opennms"
id: "minion-local"
location: "Networks"

karaf:
  shell:
    ssh:
      host: "0.0.0.0"

ipc:
  grpc:
    host: "onms.forrest.one"
    port: "8990"

netmgt:
  syslog:
    syslog.listen.interface: "0.0.0.0"
    syslog.listen.port: 1514

  traps:
    trapd.listen.interface: "0.0.0.0"
    trapd.listen.port: 1162
